#############################################################################
# Makefile for building: otpsetup.app/Contents/MacOS/otpsetup
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Sep 6 15:18:53 2015
# Project:  otpsetup.pro
# Template: app
# Command: /Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile otpsetup.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ -I. -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/Versions/4/Headers -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/Versions/4/Headers -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtGui -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtWebKit.framework/Versions/4/Headers -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtWebKit -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/include -I. -I. -F/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib -framework QtWebKit -framework QtGui -L/usr/local/pgsql/lib -L/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -F/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		otpsetup.cpp \
		otpinstall.cpp \
		otpexist.cpp \
		otpfeature.cpp moc_otpsetup.cpp \
		moc_otpinstall.cpp \
		moc_otpexist.cpp \
		moc_otpfeature.cpp \
		qrc_otpsetup.cpp
OBJECTS       = main.o \
		otpsetup.o \
		otpinstall.o \
		otpexist.o \
		otpfeature.o \
		moc_otpsetup.o \
		moc_otpinstall.o \
		moc_otpexist.o \
		moc_otpfeature.o \
		qrc_otpsetup.o
DIST          = ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		otpsetup.pro
QMAKE_TARGET  = otpsetup
DESTDIR       = 
TARGET        = otpsetup.app/Contents/MacOS/otpsetup

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile otpsetup.app/Contents/PkgInfo otpsetup.app/Contents/Resources/empty.lproj otpsetup.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_otpsetup.h ui_otpinstall.h ui_otpexist.h ui_otpfeature.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) otpsetup.app/Contents/MacOS/ || $(MKDIR) otpsetup.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: otpsetup.pro  ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/qmake.conf ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtWebKit.framework/QtWebKit.prl \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl \
		/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile otpsetup.pro
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtWebKit.framework/QtWebKit.prl:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl:
/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile otpsetup.pro

otpsetup.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) otpsetup.app/Contents || $(MKDIR) otpsetup.app/Contents 
	@$(DEL_FILE) otpsetup.app/Contents/PkgInfo
	@echo "APPL????" >otpsetup.app/Contents/PkgInfo
otpsetup.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) otpsetup.app/Contents/Resources || $(MKDIR) otpsetup.app/Contents/Resources 
	@touch otpsetup.app/Contents/Resources/empty.lproj
	
otpsetup.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) otpsetup.app/Contents || $(MKDIR) otpsetup.app/Contents 
	@$(DEL_FILE) otpsetup.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,otpsetup,g" -e "s,@TYPEINFO@,????,g" ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/Info.plist.app >otpsetup.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/otpsetup1.0.0 || $(MKDIR) .tmp/otpsetup1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/otpsetup1.0.0/ && $(COPY_FILE) --parents otpsetup.h otpinstall.h otpexist.h otpfeature.h .tmp/otpsetup1.0.0/ && $(COPY_FILE) --parents otpsetup.qrc .tmp/otpsetup1.0.0/ && $(COPY_FILE) --parents main.cpp otpsetup.cpp otpinstall.cpp otpexist.cpp otpfeature.cpp .tmp/otpsetup1.0.0/ && $(COPY_FILE) --parents otpsetup.ui otpinstall.ui otpexist.ui otpfeature.ui .tmp/otpsetup1.0.0/ && (cd `dirname .tmp/otpsetup1.0.0` && $(TAR) otpsetup1.0.0.tar otpsetup1.0.0 && $(COMPRESS) otpsetup1.0.0.tar) && $(MOVE) `dirname .tmp/otpsetup1.0.0`/otpsetup1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/otpsetup1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r otpsetup.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_otpsetup.cpp moc_otpinstall.cpp moc_otpexist.cpp moc_otpfeature.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_otpsetup.cpp moc_otpinstall.cpp moc_otpexist.cpp moc_otpfeature.cpp
moc_otpsetup.cpp: ui_otpsetup.h \
		otpsetup.h
	/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ otpsetup.h -o moc_otpsetup.cpp

moc_otpinstall.cpp: ui_otpinstall.h \
		otpinstall.h
	/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ otpinstall.h -o moc_otpinstall.cpp

moc_otpexist.cpp: ui_otpexist.h \
		otpexist.h
	/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ otpexist.h -o moc_otpexist.cpp

moc_otpfeature.cpp: ui_otpfeature.h \
		otpfeature.h
	/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ otpfeature.h -o moc_otpfeature.cpp

compiler_rcc_make_all: qrc_otpsetup.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_otpsetup.cpp
qrc_otpsetup.cpp: otpsetup.qrc \
		qss/otpsetup.qss \
		images/test.png \
		images/file.png \
		images/welcome.png \
		images/install.png \
		images/releaseinfo.png \
		images/arrow.png \
		files/releaseInfo.html \
		files/install.html \
		files/welcome.html
	/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/rcc -name otpsetup otpsetup.qrc -o qrc_otpsetup.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_otpsetup.h ui_otpinstall.h ui_otpexist.h ui_otpfeature.h
compiler_uic_clean:
	-$(DEL_FILE) ui_otpsetup.h ui_otpinstall.h ui_otpexist.h ui_otpfeature.h
ui_otpsetup.h: otpsetup.ui
	/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic otpsetup.ui -o ui_otpsetup.h

ui_otpinstall.h: otpinstall.ui
	/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic otpinstall.ui -o ui_otpinstall.h

ui_otpexist.h: otpexist.ui
	/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic otpexist.ui -o ui_otpexist.h

ui_otpfeature.h: otpfeature.ui
	/Users/ZrushZhang/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic otpfeature.ui -o ui_otpfeature.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp otpsetup.h \
		ui_otpsetup.h \
		otpinstall.h \
		ui_otpinstall.h \
		otpexist.h \
		ui_otpexist.h \
		otpfeature.h \
		ui_otpfeature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

otpsetup.o: otpsetup.cpp otpsetup.h \
		ui_otpsetup.h \
		otpinstall.h \
		ui_otpinstall.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o otpsetup.o otpsetup.cpp

otpinstall.o: otpinstall.cpp otpinstall.h \
		ui_otpinstall.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o otpinstall.o otpinstall.cpp

otpexist.o: otpexist.cpp otpexist.h \
		ui_otpexist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o otpexist.o otpexist.cpp

otpfeature.o: otpfeature.cpp otpfeature.h \
		ui_otpfeature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o otpfeature.o otpfeature.cpp

moc_otpsetup.o: moc_otpsetup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_otpsetup.o moc_otpsetup.cpp

moc_otpinstall.o: moc_otpinstall.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_otpinstall.o moc_otpinstall.cpp

moc_otpexist.o: moc_otpexist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_otpexist.o moc_otpexist.cpp

moc_otpfeature.o: moc_otpfeature.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_otpfeature.o moc_otpfeature.cpp

qrc_otpsetup.o: qrc_otpsetup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_otpsetup.o qrc_otpsetup.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

